name: curtinlv
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: curtinlv-sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync curtinlv-sync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/curtinlv/JD-Script.git"
          source_branch: "main"
          destination_branch: "curtinlv"
          github_token: ${{ secrets.PAT }}
