name: smiek2121
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: smiek2121-sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync smiek2121-sync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/smiek2121/scripts.git"
          source_branch: "master"
          destination_branch: "smiek2121"
          github_token: ${{ secrets.PAT }}
